version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  web:
    build: .
    volumes:
      - ./develop:/var/www/html
    depends_on:
      - mysql
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
